# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23259b87ae1e6be676658fdecfe1b950114e230b8247a5ee0aa520bf1d7737435984b42b28c8883e16a19dbdddb8d3433360814ea1c2598140d98e26a8180a33

test:
  secret_key_base: e876e1c57ad2f3c00d4bfaff1c9067515128293fcbb7f27f08387101b2ee4e5285e5557ad144ffa58032630b4e152958024b7636a9f2f35df73fb776ee27ca71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
